#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20181117 - First script for updating PiHole VM
# 20200319 - Added testing disk access speed
# 20200317 - Added pihole updates
#            (1)https://www.debian.org/doc/manuals/debian-reference/ch09.en.html
# 20200331 - Combined update and log scripts together
# 20200525 - Refreshed look, added Debian versioning
#
echo "------------------------------------------"
echo "--[ Debian Version $(cat /etc/debian_version), Update? (y/n) ]--"
echo "------------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------"
  echo "--[ Updating Debian ]--"
  echo "-----------------------"
  sudo apt-get update
  echo "------------------------"
  echo "--[ Upgrading Debian ]--"
  echo "------------------------"
  sudo apt-get upgrade
  echo "-------------------------"
  echo "--[ Running autoclean ]--"
  echo "-------------------------"
  sudo apt-get autoclean
fi
echo "----------------------------"
echo "--[ Update PiHole? (y/n) ]--"
echo "----------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------"
  echo "--[ Updating PiHole ]--"
  echo "-----------------------"
  sudo pihole -up
  echo "----------------------------------------"
  echo "--[ Update PiHole - Speedtest? (y/n) ]--"
  echo "----------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  echo "-----------------------------------"
  echo "--[ Updating PiHole - Speedtest ]--"
  echo "-----------------------------------"
  sudo curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/update.sh | bash
  fi
fi
echo "------------------------"
echo "--[ Updating mlocate ]--"
echo "------------------------"
sudo updatedb
echo "-------------------------"
echo "--[ Check Logs? (y/n) ]--"
echo "-------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "---------------------------------------"
  echo "--[ Checking Unattended Updates log ]--"
  echo "---------------------------------------"
  sudo tail -n 5 /var/log/dpkg.log
  echo "---------------------------------------"
  echo "--[ Checking if fail2ban is running ]--"
  echo "---------------------------------------"
  sudo fail2ban-client status
  echo "---------------------------"
  echo "--[ Checking UFW status ]--"
  echo "---------------------------"
  sudo ufw status
  echo "--------------------------------------"
  echo "--[ Check Disk Access Speed? (y/n) ]--"
  echo "--------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "---------------------------------"
    echo "--[ Testing disk access speed ]--"
    echo "---------------------------------"
    sudo hdparm -tT /dev/sda1
  fi
  echo "--------------------------------"
  echo "--[ Run rkhunter scan? (y/n) ]--"
  echo "--------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  echo "---------------------------"
  echo "--[ Checking UFW status ]--"
  echo "---------------------------"
  sudo rkhunter --check --rwo
  fi
fi
